### ISSUE TITLE
Menu-Icon in Book disappears when Vimeo-Video is embedded

### ISSUE THREAD

**Issue by regichile** [dthies/moodle-format_popups#6] opened 2021-09-10 20:12 UTC
Hi, I have just started using the "pop up activities" Plugin for moodle. And I love it. But I ran into some trouble. 

I am using multiple Books in my moodle course. And I observed that sometimes the blue hamburger-Menu on the top left disappears. I then found out that this happens, when I had opened lastely a book with an embedded Vimeo Video. Then closed that book and opend (any) other. Always when the lastely opened book page had an embedded Vimeo Video the next opening of a book comes without that little Menue icon...

With the embed-code comes a script-code... maybe it is related to that...

> <script src="https://player.vimeo.com/api/player.js" type="text/javascript"></script>
> <div class="vimeovideo" style="padding: 56.25% 0 0 0; position: relative;"><iframe src="https://player.vimeo.com/video/599992066?badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479&amp;h=624d6a77b7" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen="" style="position: absolute; top: 0; left: 0; width: 100%; height: 100%;" title="26 Einf&amp;uuml;hrung Propheten" frameborder="0"></iframe></div>

I am using Moodle 3.10.4 and pop up activities 1.0.6

![WithMenu](https://user-images.githubusercontent.com/90478547/132911106-3d4e38a1-8a81-414a-8ebe-e56a58ea0d5e.jpg)

![WithoutMenu](https://user-images.githubusercontent.com/90478547/132911102-cee2a31d-5fb5-4449-a7cf-d60b1b474ea2.jpg)

**Comment by dthies** [comment] 2021-09-13 16:08
Thanks I had seen some stange things happen occasionally, but never connected it with the vidoetime filter. I will see what I can do.

**Comment by dthies** [comment] 2021-09-15 16:48
I have not been able to reproduce this. It is likely that it may be caused by a javascript error which occurs before the icon is shown (this is done by js after the content loads with the chapter info). The error may be cause by another plugin or something particular to your installation. If occurs again, you should check the js console in the browser developer tools to see if anything is reported there.

**Comment by dthies** [comment] 2021-11-04 17:24
I think that is probably the best solution in it works. Adding javascript in module content is potentially problematic since the module code is loaded multiple times within a page. If the code is loaded as a module as standard practice in Moodle it should work okay, but it could case clashes like this or memory leaks.  It may be worth adding a warning in the documentation, but I will close this now.

**Closed by dthies** 2021-11-04 17:24 UTC
